sudo: required

language: julia

os:
    - linux

julia:
    - nightly
    - 0.7.0

matrix:
    - PYTHON=Conda-python

install:
    - source .ci/travis.sh
    - julia .ci/install.jl

script:
    - julia test/runtests.jl

cache:
    directories:
        - $HOME/miniconda
        - $HOME/.cache/Tectonic

after_success:
    - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then source .ci/build-paper.sh; fi
