# Adapted from http://dfm.io/posts/travis-latex/
sudo: false

dist: trusty

language: python

addons:
    apt:
        packages:
            - gcc-4.8
            - g++-4.8
            - texlive-xetex
            - texlive-latex-recommended
            - texlive-latex-extra
            - texlive-fonts-recommended
            - texlive-fonts-extra
            - latex-xcolor
            - lmodern

matrix:
    include:
        - os: linux
          env: PYTHON_VERSION=3.4 NUMPY_VERSION=1.11

install:
    - source .ci/travis.sh

script:
    - py.test -v

after_success:
    - source .ci/build-paper.sh
