# Adapted from http://dfm.io/posts/travis-latex/
sudo: required

dist: trusty

language: julia

install:
    - source .ci/travis.sh

script:
    - py.test -v

after_success:
    - source .ci/build-paper.sh
