sudo: required

language: julia

os:
    - linux

julia:
    - 0.7.0

matrix:
    - PYTHON=Conda-python

#script:
#    - export LD_LIBRARY_PATH=$HOME/.julia/v0.7/Conda/deps/usr/lib

before_install:
    - julia .ci/install.jl

install:
    - source .ci/travis.sh

cache:
    directories:
        - $HOME/miniconda
        - $HOME/.cache/Tectonic

after_success:
    - source .ci/build-paper.sh
