sudo: required

language: julia

os:
    - linux

julia:
    - 0.6

matrix:
    - PYTHON=Conda-python

script:
    - export LD_LIBRARY_PATH=$HOME/.julia/v0.6/Conda/deps/usr/lib

before_install:
    - julia -e 'ENV["PYTHON"]=""; Pkg.add("Conda"); using Conda; Conda.update(); Conda.add("matplotlib"); Pkg.add("PyCall"); Pkg.build("PyCall"); Pkg.add("PyPlot"); Pkg.add("SpecialFunctions")'

install:
    - source .ci/travis.sh
    - julia -e 'Pkg.build("PyCall")'

after_success:
    - source .ci/build-paper.sh
