language: julia

os:
    - linux

julia:
    - 0.6

matrix:
    - PYTHON=Conda-python

script:
    - export LD_LIBRARY_PATH=$HOME/.julia/v0.6/Conda/deps/usr/lib #; LD_PRELOAD=${HOME}/.julia/v0.6/Conda/deps/usr/lib/libz.so julia -e 'Pkg.clone(pwd());Pkg.test("ClimateTools"; coverage=true);'

before_install:
    - julia -e 'ENV["PYTHON"]=""; Pkg.add("Conda"); using Conda; Conda.update(); Conda.add("matplotlib"); Pkg.add("PyCall"); Pkg.build("PyCall"); Pkg.add("PyPlot");'

after_success:
    - source .ci/build-paper.sh
