sudo: required

language: julia

os:
    - linux

julia:
    - nightly
    - 0.7.0

matrix:
    - PYTHON=Conda-python

addons:
    apt:
        packages:
            - gfortran

install:
    - source .ci/travis.sh
    - julia .ci/install.jl

script:
    - julia test/runtests.jl
    - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then source .ci/build-paper.sh; fi

cache:
    directories:
        - $HOME/.cache/Tectonic

after_failure:
    - sleep 3