authors = ["Eric Agol <agol@uw.edu>", "Rodrigo Luger <rodluger@gmail.com>", "Daniel Foreman-Mackey <foreman.mackey@gmail.com>"]
name = "Limbdark"
uuid = "a8ea2468-7020-11e9-21b8-e18c1ea05de2"
version = "0.1.0"

[deps]
